export type entity =
  | 'brand_product'
  | 'Banner'
  | 'Color'
  | 'ColorType'
  | 'Enterprise'
  | 'FiberType'
  | 'Firber'
  | 'PlantsType'
  | 'Products'
  | 'Raw_material'
  | 'RegionType'
  | 'UserType'
  | 'users'
  | 'Article'
  | 'Activity'
  | 'ArticleType'
