# name: Deploy to Firebase

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     - cron: '*/15 * * * *'
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build and Deploy to Firebase
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v2
#       - name: Create env file
#         run:
#           touch .env.local
#           echo API_KEY=${{ secrets.API_KEY }} >> .env
#           cat .env
#       - name: Install Dependencies
#         run: yarn
#       - name: Build
#         run: yarn build
#       - name: Export
#         run: yarn export
#       - name: Archive Production Artifact
#         uses: actions/upload-artifact@master
#         with:
#           name: out
#           path: out

#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master
#       - name: Download Artifact
#         uses: actions/download-artifact@master
#         with:
#           name: out
#           path: out
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
